version: "3.8"

services:
  main-app:
    build:
      context: ./main-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./main-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - support-app

  support-app:
    build:
      context: ./support-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./support-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
